apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-adapter-kuma
  namespace: kuma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smi-adapter-kuma
  template:
    metadata:
      labels:
        name: smi-adapter-kuma
      annotations:
        sidecar.kuma.io/inject: "false"
    spec:
      serviceAccountName: smi-adapter-kuma
      containers:
        - name: smi-adapter-kuma
          image: layer5/smi-kuma:latest
          command:
          - smi-adapter-kuma
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smi-adapter-kuma"
